import type { AppModel } from './model.js';
import type { GraphEdge,GraphNode,GraphNodeType } from './graph-data.js';
const add=(nodes:GraphNode[],edges:GraphEdge[],node:GraphNode)=>{if(!nodes.some(n=>n.id===node.id))nodes.push(node);};
const edge=(edges:GraphEdge[],from:string,to:string,type:GraphEdge['type'])=>{const id=from+'::'+type+'::'+to;if(!edges.some(e=>e.id===id))edges.push({id,from,to,type});};
export function buildMissionGraph(model:AppModel){const nodes:GraphNode[]=[];const edges:GraphEdge[]=[];const missionId=model.missionUi.id;
if(missionId){add(nodes,edges,{id:'mission:'+missionId,type:'mission',label:model.missionUi.title,status:model.missionUi.status,resource:{type:'mission',id:missionId}});}
for(const t of model.missionData.tasks){const tid='task:'+t.id;add(nodes,edges,{id:tid,type:'task',label:t.title,status:t.status,resource:{type:'task',id:t.id}});if(missionId)edge(edges,'mission:'+missionId,tid,'contains');for(const dep of t.dependsOn)edge(edges,tid,'task:'+dep,'depends-on');if(t.currentExecutionId)edge(edges,tid,'execution:'+t.currentExecutionId,'contains');if(t.assignedAgentId)edge(edges,tid,'agent:'+t.assignedAgentId,'assigned-to');if(t.assignedDeviceId)edge(edges,tid,'device:'+t.assignedDeviceId,'runs-on');}
for(const e of model.missionData.executions){const id='execution:'+e.id;add(nodes,edges,{id,type:'execution',label:e.id,status:e.status,resource:{type:'execution',id:e.id}});edge(edges,id,'task:'+e.taskId,'belongs-to');if(e.agentId)edge(edges,id,'agent:'+e.agentId,'executed-by');if(e.deviceId)edge(edges,id,'device:'+e.deviceId,'runs-on');if(e.sessionId)edge(edges,id,'session:'+e.sessionId,'belongs-to');}
for(const s of model.missionData.sessions){const id='session:'+s.id;add(nodes,edges,{id,type:'session',label:s.goal,status:s.status,resource:{type:'session',id:s.id}});if(missionId)edge(edges,'mission:'+missionId,id,'contains');for(const eid of s.executionIds)edge(edges,id,'execution:'+eid,'contains');}
for(const a of model.missionData.artifacts){const id='artifact:'+a.id;add(nodes,edges,{id,type:'artifact',label:a.path,status:a.validation,resource:{type:'artifact',id:a.id}});if(a.taskId)edge(edges,'task:'+a.taskId,id,'produced');if(a.executionId)edge(edges,'execution:'+a.executionId,id,'produced');if(a.path) {const fid='file:'+a.path;add(nodes,edges,{id:fid,type:'file',label:a.path,status:a.action,resource:{type:'file',id:a.path}});edge(edges,id,fid,'modified');}}
for(const a of model.fleet.agents){const id='agent:'+a.id;add(nodes,edges,{id,type:'agent',label:a.name,status:a.status,resource:{type:'agent',id:a.id}});if(a.currentTaskId)edge(edges,id,'task:'+a.currentTaskId,'assigned-to');if(a.currentExecutionId)edge(edges,id,'execution:'+a.currentExecutionId,'executed-by');if(a.deviceId)edge(edges,id,'device:'+a.deviceId,'runs-on');}
for(const d of model.fleet.devices){const id='device:'+d.id;add(nodes,edges,{id,type:'device',label:d.name,status:d.status,resource:{type:'device',id:d.id}});for(const aid of d.agentIds)edge(edges,id,'agent:'+aid,'contains');for(const tid of d.taskIds)edge(edges,id,'task:'+tid,'contains');}
for(const c of model.missionData.github.commits){const id='commit:'+c.hash;add(nodes,edges,{id,type:'commit',label:c.hash.slice(0,8)+' '+c.subject,resource:{type:'commit',id:c.hash}});for(const a of model.missionData.artifacts){if(a.path&&model.missionData.github.changedFiles.includes(a.path))edge(edges,'artifact:'+a.id,id,'committed-in');}}
if(model.missionData.github.pullRequest){const p=model.missionData.github.pullRequest;const id='pr:'+String(p.number);add(nodes,edges,{id,type:'pull-request',label:'#'+p.number+' '+p.title,status:p.state,resource:{type:'pull-request',id:String(p.number)}});for(const c of model.missionData.github.commits.slice(0,8))edge(edges,'commit:'+c.hash,id,'included-in');}

for(const l of [model.loop]){if(l.id){const lid='loop:'+l.id;add(nodes,edges,{id:lid,type:'loop',label:'Loop '+String(l.iteration),status:l.status,resource:{type:'loop',id:l.id}});if(missionId)edge(edges,'mission:'+missionId,lid,'contains');for(const it of l.iterations){const iid='iteration:'+it.id;add(nodes,edges,{id:iid,type:'iteration',label:'Iteration '+it.number,status:it.status,resource:{type:'iteration',id:it.id}});edge(edges,lid,iid,'contains');for(const did of it.decisionIds)edge(edges,iid,'decision:'+did,'produced');if(it.planId)edge(edges,iid,'plan:'+it.planId,'produced');for(const eid of it.executionIds)edge(edges,iid,'execution:'+eid,'contains');}}}
for(const d of model.decisions.records){const did='decision:'+d.id;add(nodes,edges,{id:did,type:'decision',label:'#'+d.id+' '+d.action,status:d.status,resource:{type:'decision',id:d.id}});if(d.loopId)edge(edges,'loop:'+d.loopId,did,'produced');if(d.iterationId)edge(edges,'iteration:'+d.iterationId,did,'produced');if(d.targetResource)edge(edges,did,d.targetResource.type+':'+d.targetResource.id,'contains');for(const e of d.evidenceIds)edge(edges,did,'evidence:'+e,'validated-by');if(d.graphVersion!=null){} }
for(const p of model.decisions.plans){const pid='plan:'+p.id;add(nodes,edges,{id:pid,type:'plan',label:p.objective,status:p.status,resource:{type:'plan',id:p.id}});if(p.loopId)edge(edges,'loop:'+p.loopId,pid,'produced');if(p.iterationId)edge(edges,'iteration:'+p.iterationId,pid,'produced');}
for(const a of model.approvals.requests){const aid='approval:'+a.id;add(nodes,edges,{id:aid,type:'approval',label:a.action,status:a.status,resource:{type:'approval',id:a.id}});if(a.decisionId)edge(edges,'decision:'+a.decisionId,aid,'requires');if(missionId)edge(edges,'mission:'+missionId,aid,'contains');}
return {nodes,edges};}
