import type { AppModel } from '../model.js';
import type { Layout } from '../layout.js';
import {fit,truncate} from '../terminal/text.js';
import {BOLD,DIM,FG,styled} from '../terminal/ansi.js';
import {onChat} from '../theme.js';
import {selectCurrentFleetAgent,selectCurrentFleetDevice,selectFleetAgents,selectFleetDevices} from '../state/fleet-projections.js';
import {selectFocusedGraphNode,selectGraphNeighbors} from '../state/graph-projections.js';

const statusIcon=(s:string)=>s==='running'||s==='connected'||s==='healthy'?styled('●',FG.GREEN):s==='error'||s==='failed'||s==='disconnected'||s==='offline'||s==='unhealthy'?styled('!',FG.RED):s==='busy'||s==='starting'?styled('→',FG.YELLOW):styled('○',DIM,FG.WHITE);
const pad=(lines:string[],layout:Layout,s:string)=>lines.push(onChat(fit(s,layout.mainWidth)));
export function renderFleet(model:AppModel,layout:Layout):string[]{const lines:string[]=[];pad(lines,layout,'  '+styled('FLEET',BOLD,FG.CYAN)+'  '+styled(String(model.fleet.agents.length)+' AGENTS',DIM,FG.WHITE)+'  '+styled(String(model.fleet.devices.length)+' DEVICES',DIM,FG.WHITE));pad(lines,layout,'  '+styled('─'.repeat(Math.max(0,layout.mainWidth-4)),DIM,FG.BRIGHT_BLACK));const agents=selectFleetAgents(model);const devices=selectFleetDevices(model);if(!agents.length&&!devices.length)pad(lines,layout,'  '+styled('No runtime fleet data yet. Agents appear as the mission runtime starts them; devices appear when reported by the runtime.',DIM,FG.WHITE));if(agents.length){pad(lines,layout,'  '+styled('AGENTS',BOLD,FG.BRIGHT_WHITE));for(const a of agents)pad(lines,layout,'  '+statusIcon(a.status)+' '+styled(truncate(a.name,22),BOLD,FG.WHITE)+'  '+truncate(a.status.toUpperCase(),12)+'  task:'+(a.currentTaskId??'—')+'  exec:'+(a.currentExecutionId??'—')+'  device:'+(a.deviceId??'—'));}if(devices.length){pad(lines,layout,'');pad(lines,layout,'  '+styled('DEVICES',BOLD,FG.BRIGHT_WHITE));for(const d of devices)pad(lines,layout,'  '+statusIcon(d.status)+' '+styled(truncate(d.name,22),BOLD,FG.WHITE)+'  '+d.status.toUpperCase()+'  agents:'+d.agentIds.length+'  tasks:'+d.taskIds.length+'  '+d.health.toUpperCase());}const a=selectCurrentFleetAgent(model),d=selectCurrentFleetDevice(model);if(a||d){pad(lines,layout,'');pad(lines,layout,'  '+styled('FOCUS',BOLD,FG.BRIGHT_WHITE));if(a){pad(lines,layout,'  Agent        '+a.name);pad(lines,layout,'  Status       '+a.status);pad(lines,layout,'  Task         '+(a.currentTaskId??'—'));pad(lines,layout,'  Execution    '+(a.currentExecutionId??'—'));pad(lines,layout,'  Device       '+(a.deviceId??'—'));pad(lines,layout,'  Capabilities '+(a.capabilities.length?a.capabilities.join(' · '):'—'));pad(lines,layout,'  Health       '+a.health.toUpperCase());}else if(d){pad(lines,layout,'  Device       '+d.name);pad(lines,layout,'  Status       '+d.status);pad(lines,layout,'  Agents       '+(d.agentIds.length?d.agentIds.join(', '):'—'));pad(lines,layout,'  Tasks        '+(d.taskIds.length?d.taskIds.join(', '):'—'));pad(lines,layout,'  Capabilities '+(d.capabilities.length?d.capabilities.join(' · '):'—'));pad(lines,layout,'  Health       '+d.health.toUpperCase());}}while(lines.length<layout.viewportHeight)pad(lines,layout,'');return lines.slice(0,layout.viewportHeight);}
export function renderGraph(model:AppModel,layout:Layout):string[]{const lines:string[]=[];const nodes=model.graph.nodes;const edges=model.graph.edges;pad(lines,layout,'  '+styled('COGNITIVE GRAPH',BOLD,FG.CYAN)+'  '+styled(String(nodes.length)+' NODES',DIM,FG.WHITE)+'  '+styled(String(edges.length)+' RELATIONSHIPS',DIM,FG.WHITE));pad(lines,layout,'  '+styled('─'.repeat(Math.max(0,layout.mainWidth-4)),DIM,FG.BRIGHT_BLACK));if(!nodes.length){pad(lines,layout,'  '+styled('No graph yet. Start a mission to populate mission, task, execution, agent, artifact and Git relationships.',DIM,FG.WHITE));while(lines.length<layout.viewportHeight)pad(lines,layout,'');return lines.slice(0,layout.viewportHeight);}const focus=selectFocusedGraphNode(model)??nodes[0]!;pad(lines,layout,'  FOCUS  '+styled(focus.label,BOLD,FG.BRIGHT_WHITE)+'  ['+focus.type.toUpperCase()+']  '+(focus.status??''));pad(lines,layout,'  Resource '+focus.resource.type+':'+focus.resource.id);pad(lines,layout,'');const neighbors=selectGraphNeighbors(model,focus.id);if(neighbors.length){pad(lines,layout,'  '+styled('RELATIONSHIPS',BOLD,FG.WHITE));for(const n of neighbors.slice(0,Math.max(1,layout.viewportHeight-10)))pad(lines,layout,'  '+statusIcon(n.status??'')+' '+styled(n.type.toUpperCase(),DIM,FG.WHITE)+'  '+truncate(n.label,layout.mainWidth-34));}else pad(lines,layout,'  '+styled('No connected resources.',DIM,FG.WHITE));pad(lines,layout,'');pad(lines,layout,'  '+styled('TRACE',BOLD,FG.WHITE));const path=model.graph.focus.path??[];pad(lines,layout,path.length?path.map(id=>nodes.find(n=>n.id===id)?.label??id).join('  →  '):'Select a relationship to build a trace.');pad(lines,layout,'');pad(lines,layout,styled('↑/↓ select  Enter inspect  → expand  ← collapse  T task  F fleet',DIM,FG.WHITE));while(lines.length<layout.viewportHeight)pad(lines,layout,'');return lines.slice(0,layout.viewportHeight);}
