import type { UniversalAgentDefinition, UniversalCapabilities } from './types.js';

const base = (overrides: Partial<UniversalCapabilities> = {}): UniversalCapabilities => ({
  codeGeneration: true, fileEditing: true, commandExecution: true, webResearch: false,
  browser: false, longContext: false, multimodal: false, planning: true, testing: true,
  debugging: true, refactoring: true, git: true, mcp: false, acp: false, a2a: false,
  subagents: false, interactive: true, nativeTui: true, headless: false, local: true,
  cloud: true, persistentSessions: false, resumeSessions: false, streaming: true,
  structuredOutput: false, sandboxing: false, remoteExecution: false, ...overrides,
});

const cli = (
  id: string, name: string, provider: string, executable: string,
  installation: UniversalAgentDefinition['installation'],
  capabilities: Partial<UniversalCapabilities> = {},
  extra: Partial<UniversalAgentDefinition> = {},
): UniversalAgentDefinition => ({
  id, name, provider, kind: 'cli', integrationStatus: 'supported',
  protocols: ['pty', 'stdio'], platforms: ['darwin', 'linux', 'win32'],
  capabilities: base({ ...capabilities, headless: capabilities.headless ?? Boolean(extra.runArgs) }), installation, executableCandidates: [executable],
  versionArgs: ['--version'], promptDelivery: extra.runArgs ? 'argv' : 'interactive-stdin', authentication: { methods: ['environment', 'api-key', 'oauth'], environmentVariables: provider === 'openai' ? ['OPENAI_API_KEY'] : provider === 'anthropic' ? ['ANTHROPIC_API_KEY'] : provider === 'google' ? ['GEMINI_API_KEY', 'GOOGLE_API_KEY'] : provider === 'mistral' ? ['MISTRAL_API_KEY'] : provider === 'moonshot' ? ['MOONSHOT_API_KEY'] : provider === 'deepseek' ? ['DEEPSEEK_API_KEY'] : [] },
  ...extra,
});

export const UNIVERSAL_AGENT_CATALOG: UniversalAgentDefinition[] = [
  cli('opencode', 'OpenCode', 'opencode', 'opencode',
    { strategy: 'npm', package: 'opencode-ai', command: 'npm install -g opencode-ai' },
    { webResearch: true, longContext: true, local: true, cloud: true },
    { integrationStatus: 'production', upstreamUrl: 'https://opencode.ai' }),
  cli('claude-code', 'Claude Code', 'anthropic', 'claude',
    { strategy: 'npm', package: '@anthropic-ai/claude-code', command: 'npm install -g @anthropic-ai/claude-code' },
    { webResearch: true, longContext: true, local: false, cloud: true },
    { integrationStatus: 'production', upstreamUrl: 'https://docs.anthropic.com/en/docs/claude-code' }),
  cli('gemini-cli', 'Gemini CLI', 'google', 'gemini',
    { strategy: 'npm', package: '@google/gemini-cli', command: 'npm install -g @google/gemini-cli' },
    { webResearch: true, longContext: true, multimodal: true, local: false, cloud: true },
    { integrationStatus: 'production', upstreamUrl: 'https://github.com/google-gemini/gemini-cli' }),
  cli('aider', 'Aider', 'aider', 'aider',
    { strategy: 'pip', package: 'aider-chat', command: 'python -m pip install aider-chat' },
    { webResearch: false, longContext: false, local: true, cloud: true },
    { upstreamUrl: 'https://aider.chat' }),
  cli('goose', 'Goose', 'block', 'goose',
    { strategy: 'manual', notes: 'Use the official Goose installer for the target platform.' },
    { mcp: true },
    { upstreamUrl: 'https://block.github.io/goose/' }),
  cli('codex-cli', 'Codex CLI', 'openai', 'codex',
    { strategy: 'npm', package: '@openai/codex', command: 'npm install -g @openai/codex' },
    { longContext: true, cloud: true },
    { integrationStatus: 'production', upstreamUrl: 'https://github.com/openai/codex' }),
  cli('deepseek-harness', 'DeepSeek Harness', 'deepseek', 'dsh',
    { strategy: 'manual', package: '@deepseek-ai/dsh', notes: 'Install the DeepSeek harness/provider separately.' },
    { webResearch: true, longContext: true },
    { kind: 'harness', upstreamUrl: 'https://www.deepseek.com' }),

  cli('qwen-code', 'Qwen Code', 'qwen', 'qwen',
    { strategy: 'npm', package: '@qwen-code/qwen-code', command: 'npm install -g @qwen-code/qwen-code' },
    { webResearch: true, longContext: true },
    { upstreamUrl: 'https://github.com/QwenLM/qwen-code' }),
  cli('kimi-code', 'Kimi Code', 'moonshot', 'kimi',
    { strategy: 'script', notes: 'Use the official Kimi Code installer for the target platform; EamilOS will not execute remote scripts automatically.' },
    { longContext: true, nativeTui: true },
    { upstreamUrl: 'https://github.com/MoonshotAI/kimi-cli' }),
  cli('mistral-vibe', 'Mistral Vibe', 'mistral', 'vibe',
    { strategy: 'script', notes: 'Use the official Mistral Vibe installer for the target platform; EamilOS will not execute remote scripts automatically.' },
    { longContext: true, acp: true },
    { upstreamUrl: 'https://github.com/mistralai/mistral-vibe' }),
  cli('cline-cli', 'Cline CLI', 'cline', 'cline',
    { strategy: 'npm', package: 'cline', command: 'npm install -g cline' },
    { mcp: true },
    { upstreamUrl: 'https://github.com/cline/cline', runArgs: (prompt: string) => [prompt], promptDelivery: 'argv' }),
  cli('kilo-code', 'Kilo Code', 'kilo', 'kilo',
    { strategy: 'npm', package: '@kilocode/cli', command: 'npm install -g @kilocode/cli' },
    { mcp: true },
    { upstreamUrl: 'https://github.com/Kilo-Org/kilocode', runArgs: (prompt: string) => ['run', '--auto', prompt], promptDelivery: 'argv' }),
  cli('openhands', 'OpenHands', 'openhands', 'openhands',
    { strategy: 'uv', package: 'openhands-ai', command: 'uv tool install openhands-ai' },
    { browser: true, webResearch: true, subagents: true, mcp: true },
    { integrationStatus: 'experimental', upstreamUrl: 'https://github.com/All-Hands-AI/OpenHands' }),
  cli('pi', 'Pi', 'pi', 'pi',
    { strategy: 'npm', package: '@earendil-works/pi-coding-agent', command: 'npm install -g --ignore-scripts @earendil-works/pi-coding-agent' },
    { mcp: true },
    { upstreamUrl: 'https://github.com/badlogic/pi-mono' }),
  cli('hermes-agent', 'Hermes Agent', 'nous', 'hermes',
    { strategy: 'manual', notes: 'Use the upstream Hermes Agent installer/release.' },
    { webResearch: true, browser: true, subagents: true },
    { upstreamUrl: 'https://github.com/NousResearch/hermes-agent' }),
  cli('deep-agents-code', 'Deep Agents Code', 'deep-agents', 'deepagents',
    { strategy: 'pip', package: 'deepagents', command: 'python -m pip install deepagents' },
    { subagents: true, planning: true },
    { upstreamUrl: 'https://github.com/langchain-ai/deepagents' }),
  cli('crush', 'Crush', 'charm', 'crush',
    { strategy: 'binary', notes: 'Install the official Crush binary/release.' },
    { mcp: true },
    { upstreamUrl: 'https://github.com/charmbracelet/crush' }),
  cli('grok-build', 'Grok Build', 'xai', 'grok',
    { strategy: 'provider', notes: 'Provider availability/install mechanism is environment dependent.' },
    { cloud: true, local: false },
    { integrationStatus: 'experimental' }),
  cli('open-interpreter', 'Open Interpreter', 'open-interpreter', 'interpreter',
    { strategy: 'pip', package: 'open-interpreter', command: 'python -m pip install open-interpreter' },
    { webResearch: true, multimodal: true },
    { upstreamUrl: 'https://github.com/OpenInterpreter/open-interpreter' }),
  cli('trae-agent', 'Trae Agent', 'trae', 'trae-agent',
    { strategy: 'pip', package: 'trae-agent', command: 'python -m pip install trae-agent' },
    { webResearch: true },
    { upstreamUrl: 'https://github.com/bytedance/trae-agent' }),
  cli('forgecode', 'ForgeCode', 'forgecode', 'forge',
    { strategy: 'npm', package: 'forgecode', command: 'npm install -g forgecode' },
    { mcp: true },
    { integrationStatus: 'experimental' }),
  cli('letta-code', 'Letta Code', 'letta', 'letta',
    { strategy: 'npm', package: '@letta-ai/letta-code', command: 'npm install -g @letta-ai/letta-code' },
    { persistentSessions: true, resumeSessions: true, mcp: true },
    { upstreamUrl: 'https://github.com/letta-ai/letta-code' }),
  cli('continue-cli', 'Continue CLI', 'continue', 'cn',
    { strategy: 'npm', package: '@continuedev/cli', command: 'npm install -g @continuedev/cli' },
    { mcp: true, headless: true },
    { upstreamUrl: 'https://github.com/continuedev/continue' }),
  cli('swe-agent', 'SWE-agent', 'princeton', 'sweagent',
    { strategy: 'pip', package: 'swe-agent', command: 'python -m pip install sweagent' },
    { planning: true, testing: true },
    { upstreamUrl: 'https://github.com/SWE-agent/SWE-agent' }),
  cli('plandex', 'Plandex', 'plandex', 'plandex',
    { strategy: 'binary', notes: 'Install the official Plandex binary.' },
    { longContext: true, planning: true },
    { upstreamUrl: 'https://github.com/plandex-ai/plandex' }),
  cli('opensquilla', 'OpenSquilla', 'opensquilla', 'opensquilla',
    { strategy: 'manual', notes: 'Install from the upstream project release.' },
    {},
    { integrationStatus: 'experimental' }),
  cli('gptme', 'gptme', 'gptme', 'gptme',
    { strategy: 'pip', package: 'gptme', command: 'python -m pip install gptme' },
    { webResearch: true, mcp: true },
    { upstreamUrl: 'https://github.com/gptme/gptme' }),
  cli('kode-cli', 'Kode CLI', 'kode', 'kode',
    { strategy: 'npm', package: '@shareai-lab/kode', command: 'npm install -g @shareai-lab/kode' },
    { mcp: true },
    { integrationStatus: 'experimental' }),
  cli('codebuff', 'Codebuff', 'codebuff', 'codebuff',
    { strategy: 'npm', package: 'codebuff', command: 'npm install -g codebuff' },
    { subagents: true },
    { upstreamUrl: 'https://github.com/CodebuffAI/codebuff' }),
  cli('amazon-q', 'Amazon Q Developer CLI', 'aws', 'q',
    { strategy: 'binary', notes: 'Install the official Amazon Q Developer CLI.' },
    { webResearch: true, cloud: true },
    { upstreamUrl: 'https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/command-line.html' }),
  cli('github-copilot', 'GitHub Copilot CLI', 'github', 'copilot',
    { strategy: 'provider', notes: 'Install using the current official GitHub Copilot CLI distribution.' },
    { cloud: true },
    { integrationStatus: 'experimental', upstreamUrl: 'https://github.com/github/copilot-cli' }),
  cli('cursor-cli', 'Cursor CLI', 'cursor', 'cursor',
    { strategy: 'provider', notes: 'Install the current Cursor CLI distribution when available for the platform.' },
    { cloud: true },
    { integrationStatus: 'experimental' }),
  cli('kiro-cli', 'Kiro CLI', 'aws', 'kiro-cli',
    { strategy: 'provider', notes: 'Install the official Kiro CLI distribution.' },
    { cloud: true },
    { integrationStatus: 'experimental' }),
  cli('auggie', 'Auggie', 'augment', 'auggie',
    { strategy: 'provider', notes: 'Install the official Augment/Auggie CLI distribution.' },
    { cloud: true, longContext: true },
    { integrationStatus: 'experimental' }),
  cli('amp', 'Amp', 'sourcegraph', 'amp',
    { strategy: 'provider', notes: 'Install the official Amp CLI distribution.' },
    { cloud: true, subagents: true },
    { upstreamUrl: 'https://ampcode.com' }),
];

export function getUniversalAgentDefinition(id: string): UniversalAgentDefinition | undefined {
  return UNIVERSAL_AGENT_CATALOG.find((agent) => agent.id === id);
}
