import Database from 'better-sqlite3';
import { createHash } from 'node:crypto';
import type { AgentCard, CapabilityAdvertisement } from './EamilosA2AProtocol.js';
import type { DistributedEventLog } from './EamilosDistributedEventLog.js';

export type FleetWorkerStatus = 'online' | 'stale' | 'offline';
export interface FleetWorker {
  workerId:string; agentId:string; harnessId:string; name:string; description:string; endpoint:string;
  capabilities:string[]; maxConcurrency:number; activeExecutions:number; capacity:number; streaming:boolean;
  checkpointResume:boolean; authentication:string[]; metadata:Record<string,unknown>; status:FleetWorkerStatus;
  advertisedAt:string; lastHeartbeatAt:string; heartbeatSequence:number; revision:number; updatedAt:string;
}
export interface FleetHeartbeat { workerId:string; timestamp:string; activeExecutions:number; capacity:number; sequence:number; }
export interface FleetRegistryOptions { staleAfterMs?:number; offlineAfterMs?:number; eventLog?:DistributedEventLog; }
export interface FleetRegistry {
  register(card:AgentCard, advertisement?:CapabilityAdvertisement):FleetWorker;
  heartbeat(heartbeat:FleetHeartbeat):FleetWorker;
  unregister(workerId:string):FleetWorker|undefined;
  get(workerId:string):FleetWorker|undefined;
  list():FleetWorker[];
  find(capabilities?:string[], options?:{includeStale?:boolean;limit?:number}):FleetWorker[];
  refreshStatuses(now?:number):FleetWorker[];
  close?():void;
}
export class FleetRegistryConflictError extends Error {
  readonly code='FLEET_REGISTRY_CONFLICT' as const;
  constructor(message:string){super(message);this.name='FleetRegistryConflictError';}
}
const SCHEMA_VERSION=1;
const caps=(v:string[])=>[...new Set(v.filter(Boolean))].sort();
function validate(h:FleetHeartbeat){if(!h.workerId)throw new Error('INVALID_WORKER_ID');if(!Number.isInteger(h.activeExecutions)||h.activeExecutions<0)throw new Error('INVALID_ACTIVE_EXECUTIONS');if(!Number.isInteger(h.capacity)||h.capacity<0)throw new Error('INVALID_CAPACITY');if(!Number.isInteger(h.sequence)||h.sequence<0)throw new Error('INVALID_HEARTBEAT_SEQUENCE');if(Number.isNaN(Date.parse(h.timestamp)))throw new Error('INVALID_HEARTBEAT_TIMESTAMP');}
function status(w:FleetWorker,now:number,stale:number,offline:number):FleetWorkerStatus{const age=Math.max(0,now-Date.parse(w.lastHeartbeatAt));return age>=offline?'offline':age>=stale?'stale':'online';}
function eventId(type:string,w:FleetWorker,seq?:number){return createHash('sha256').update([type,w.workerId,w.revision,seq??''].join(':')).digest('hex');}
function emit(log:DistributedEventLog|undefined,type:string,w:FleetWorker,seq?:number){if(!log)return;log.append({eventId:eventId(type,w,seq),eventType:type,workerId:w.workerId,agentId:w.agentId,harnessId:w.harnessId,occurredAt:w.updatedAt,payload:w as unknown as Record<string,unknown>});}
function make(card:AgentCard,ad?:CapabilityAdvertisement,old?:FleetWorker):FleetWorker{const now=new Date().toISOString();const max=ad?.maxConcurrency??card.maxConcurrency;const active=ad?.activeExecutions??0;return{workerId:card.workerId,agentId:card.agentId,harnessId:card.harnessId,name:card.name,description:card.description,endpoint:card.endpoint,capabilities:caps(ad?.capabilities??card.capabilities),maxConcurrency:max,activeExecutions:active,capacity:Math.max(0,ad?.maxConcurrency===undefined?max-active:Math.min(ad.maxConcurrency,Math.max(0,max-active))),streaming:card.streaming,checkpointResume:card.checkpointResume,authentication:[...card.authentication],metadata:{...card.metadata,...(ad?.metadata??{})},status:'online',advertisedAt:ad?.advertisedAt??card.advertisedAt,lastHeartbeatAt:now,heartbeatSequence:old?.heartbeatSequence??0,revision:(old?.revision??0)+1,updatedAt:now};}

export class EamilosInMemoryFleetRegistry implements FleetRegistry {
  private workers=new Map<string,FleetWorker>(); private staleAfterMs:number; private offlineAfterMs:number; private eventLog?:DistributedEventLog;
  constructor(o:FleetRegistryOptions={}){this.staleAfterMs=Math.max(1,o.staleAfterMs??30_000);this.offlineAfterMs=Math.max(this.staleAfterMs,o.offlineAfterMs??120_000);if(o.offlineAfterMs!==undefined&&o.offlineAfterMs<this.staleAfterMs)throw new Error('offlineAfterMs must be >= staleAfterMs');this.eventLog=o.eventLog;}
  register(card:AgentCard,ad?:CapabilityAdvertisement){const old=this.workers.get(card.workerId);if(old&&(old.agentId!==card.agentId||old.harnessId!==card.harnessId||old.endpoint!==card.endpoint))throw new FleetRegistryConflictError('WORKER_IDENTITY_CONFLICT');const w=make(card,ad,old);this.workers.set(w.workerId,w);emit(this.eventLog,old?'fleet.worker.updated':'fleet.worker.registered',w);return this.get(w.workerId)!;}
  heartbeat(h:FleetHeartbeat){validate(h);const old=this.workers.get(h.workerId);if(!old)throw new FleetRegistryConflictError('UNKNOWN_WORKER');if(h.sequence<=old.heartbeatSequence)throw new FleetRegistryConflictError('HEARTBEAT_SEQUENCE_REGRESSION');if(Date.parse(h.timestamp)<Date.parse(old.lastHeartbeatAt))throw new FleetRegistryConflictError('HEARTBEAT_TIME_REGRESSION');const w={...old,activeExecutions:h.activeExecutions,capacity:h.capacity,status:'online' as const,lastHeartbeatAt:h.timestamp,heartbeatSequence:h.sequence,revision:old.revision+1,updatedAt:new Date().toISOString()};this.workers.set(w.workerId,w);emit(this.eventLog,'fleet.worker.heartbeat',w,h.sequence);return this.get(w.workerId)!;}
  unregister(id:string){const old=this.workers.get(id);if(!old)return undefined;const w={...old,status:'offline' as const,revision:old.revision+1,updatedAt:new Date().toISOString()};this.workers.set(id,w);emit(this.eventLog,'fleet.worker.unregistered',w);return this.get(id);}
  get(id:string){const w=this.workers.get(id);return w?{...w,capabilities:[...w.capabilities],authentication:[...w.authentication],metadata:{...w.metadata}}:undefined;}
  list(){return [...this.workers.keys()].map(id=>this.get(id)!);}
  find(required:string[]=[],o:{includeStale?:boolean;limit?:number}={}){const set=new Set(required);const out=this.list().filter(w=>(w.status==='online'||(o.includeStale&&w.status==='stale'))&&[...set].every(c=>w.capabilities.includes(c))&&w.capacity>0);out.sort((a,b)=>b.capacity-a.capacity||a.workerId.localeCompare(b.workerId));return o.limit===undefined?out:out.slice(0,Math.max(0,o.limit));}
  refreshStatuses(now=Date.now()){for(const old of this.workers.values()){const s=status(old,now,this.staleAfterMs,this.offlineAfterMs);if(s!==old.status){const w={...old,status:s,revision:old.revision+1,updatedAt:new Date(now).toISOString()};this.workers.set(w.workerId,w);emit(this.eventLog,s==='offline'?'fleet.worker.offline':'fleet.worker.stale',w);}}return this.list();}
}

export class EamilosSqliteFleetRegistry implements FleetRegistry {
  private db:Database.Database; private staleAfterMs:number; private offlineAfterMs:number; private eventLog?:DistributedEventLog;
  constructor(o:FleetRegistryOptions&{filename:string;busyTimeoutMs?:number}){this.staleAfterMs=Math.max(1,o.staleAfterMs??30_000);this.offlineAfterMs=Math.max(this.staleAfterMs,o.offlineAfterMs??120_000);if(o.offlineAfterMs!==undefined&&o.offlineAfterMs<this.staleAfterMs)throw new Error('offlineAfterMs must be >= staleAfterMs');this.eventLog=o.eventLog;this.db=new Database(o.filename);this.db.pragma(`busy_timeout = ${Math.max(0,Math.floor(o.busyTimeoutMs??5000))}`);this.db.pragma('foreign_keys = ON');if(o.filename!==':memory:')this.db.pragma('journal_mode = WAL');this.migrate();}
  register(card:AgentCard,ad?:CapabilityAdvertisement){return this.db.transaction(()=>{const old=this.get(card.workerId);if(old&&(old.agentId!==card.agentId||old.harnessId!==card.harnessId||old.endpoint!==card.endpoint))throw new FleetRegistryConflictError('WORKER_IDENTITY_CONFLICT');const w=make(card,ad,old);this.db.prepare(`INSERT INTO eamilos_fleet_workers VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(worker_id) DO UPDATE SET agent_id=excluded.agent_id,harness_id=excluded.harness_id,name=excluded.name,description=excluded.description,endpoint=excluded.endpoint,capabilities_json=excluded.capabilities_json,max_concurrency=excluded.max_concurrency,active_executions=excluded.active_executions,capacity=excluded.capacity,streaming=excluded.streaming,checkpoint_resume=excluded.checkpoint_resume,authentication_json=excluded.authentication_json,metadata_json=excluded.metadata_json,status=excluded.status,advertised_at=excluded.advertised_at,last_heartbeat_at=excluded.last_heartbeat_at,heartbeat_sequence=excluded.heartbeat_sequence,revision=excluded.revision,updated_at=excluded.updated_at`).run(w.workerId,w.agentId,w.harnessId,w.name,w.description,w.endpoint,JSON.stringify(w.capabilities),w.maxConcurrency,w.activeExecutions,w.capacity,w.streaming?1:0,w.checkpointResume?1:0,JSON.stringify(w.authentication),JSON.stringify(w.metadata),w.status,w.advertisedAt,w.lastHeartbeatAt,w.heartbeatSequence,w.revision,w.updatedAt);emit(this.eventLog,old?'fleet.worker.updated':'fleet.worker.registered',w);return w;})(); }
  heartbeat(h:FleetHeartbeat){return this.db.transaction(()=>{validate(h);const old=this.get(h.workerId);if(!old)throw new FleetRegistryConflictError('UNKNOWN_WORKER');if(h.sequence<=old.heartbeatSequence)throw new FleetRegistryConflictError('HEARTBEAT_SEQUENCE_REGRESSION');if(Date.parse(h.timestamp)<Date.parse(old.lastHeartbeatAt))throw new FleetRegistryConflictError('HEARTBEAT_TIME_REGRESSION');const w={...old,activeExecutions:h.activeExecutions,capacity:h.capacity,status:'online' as const,lastHeartbeatAt:h.timestamp,heartbeatSequence:h.sequence,revision:old.revision+1,updatedAt:new Date().toISOString()};this.db.prepare('UPDATE eamilos_fleet_workers SET active_executions=?,capacity=?,status=?,last_heartbeat_at=?,heartbeat_sequence=?,revision=?,updated_at=? WHERE worker_id=?').run(w.activeExecutions,w.capacity,w.status,w.lastHeartbeatAt,w.heartbeatSequence,w.revision,w.updatedAt,w.workerId);emit(this.eventLog,'fleet.worker.heartbeat',w,h.sequence);return w;})(); }
  unregister(id:string){return this.db.transaction(()=>{const old=this.get(id);if(!old)return undefined;const w={...old,status:'offline' as const,revision:old.revision+1,updatedAt:new Date().toISOString()};this.db.prepare('UPDATE eamilos_fleet_workers SET status=?,revision=?,updated_at=? WHERE worker_id=?').run(w.status,w.revision,w.updatedAt,id);emit(this.eventLog,'fleet.worker.unregistered',w);return w;})(); }
  get(id:string){const r=this.db.prepare('SELECT * FROM eamilos_fleet_workers WHERE worker_id=?').get(id) as WorkerRow|undefined;return r?hydrate(r):undefined;}
  list(){return(this.db.prepare('SELECT * FROM eamilos_fleet_workers ORDER BY worker_id').all() as WorkerRow[]).map(hydrate);}
  find(required:string[]=[],o:{includeStale?:boolean;limit?:number}={}){const set=new Set(required);const out=this.list().filter(w=>(w.status==='online'||(o.includeStale&&w.status==='stale'))&&[...set].every(c=>w.capabilities.includes(c))&&w.capacity>0);out.sort((a,b)=>b.capacity-a.capacity||a.workerId.localeCompare(b.workerId));return o.limit===undefined?out:out.slice(0,Math.max(0,o.limit));}
  refreshStatuses(now=Date.now()){for(const old of this.list()){const s=status(old,now,this.staleAfterMs,this.offlineAfterMs);if(s!==old.status){const w={...old,status:s,revision:old.revision+1,updatedAt:new Date(now).toISOString()};this.db.prepare('UPDATE eamilos_fleet_workers SET status=?,revision=?,updated_at=? WHERE worker_id=?').run(s,w.revision,w.updatedAt,w.workerId);emit(this.eventLog,s==='offline'?'fleet.worker.offline':'fleet.worker.stale',w);}}return this.list();}
  close(){if(this.db.open)this.db.close();}
  private migrate(){this.db.exec('CREATE TABLE IF NOT EXISTS eamilos_fleet_schema_migrations(version INTEGER PRIMARY KEY NOT NULL, applied_at TEXT NOT NULL);');const v=this.db.prepare('SELECT MAX(version) version FROM eamilos_fleet_schema_migrations').get() as {version?:number|null};if((v.version??0)>=SCHEMA_VERSION)return;this.db.transaction(()=>{this.db.exec(`CREATE TABLE eamilos_fleet_workers(worker_id TEXT PRIMARY KEY,agent_id TEXT NOT NULL,harness_id TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL,endpoint TEXT NOT NULL,capabilities_json TEXT NOT NULL,max_concurrency INTEGER NOT NULL,active_executions INTEGER NOT NULL,capacity INTEGER NOT NULL,streaming INTEGER NOT NULL,checkpoint_resume INTEGER NOT NULL,authentication_json TEXT NOT NULL,metadata_json TEXT NOT NULL,status TEXT NOT NULL,advertised_at TEXT NOT NULL,last_heartbeat_at TEXT NOT NULL,heartbeat_sequence INTEGER NOT NULL,revision INTEGER NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX idx_fleet_status ON eamilos_fleet_workers(status);CREATE INDEX idx_fleet_heartbeat ON eamilos_fleet_workers(last_heartbeat_at);`);this.db.prepare('INSERT INTO eamilos_fleet_schema_migrations VALUES(?,?)').run(SCHEMA_VERSION,new Date().toISOString());})(); }
}
type WorkerRow={worker_id:string;agent_id:string;harness_id:string;name:string;description:string;endpoint:string;capabilities_json:string;max_concurrency:number;active_executions:number;capacity:number;streaming:number;checkpoint_resume:number;authentication_json:string;metadata_json:string;status:FleetWorkerStatus;advertised_at:string;last_heartbeat_at:string;heartbeat_sequence:number;revision:number;updated_at:string};
function hydrate(r:WorkerRow):FleetWorker{return{workerId:r.worker_id,agentId:r.agent_id,harnessId:r.harness_id,name:r.name,description:r.description,endpoint:r.endpoint,capabilities:JSON.parse(r.capabilities_json),maxConcurrency:r.max_concurrency,activeExecutions:r.active_executions,capacity:r.capacity,streaming:Boolean(r.streaming),checkpointResume:Boolean(r.checkpoint_resume),authentication:JSON.parse(r.authentication_json),metadata:JSON.parse(r.metadata_json),status:r.status,advertisedAt:r.advertised_at,lastHeartbeatAt:r.last_heartbeat_at,heartbeatSequence:r.heartbeat_sequence,revision:r.revision,updatedAt:r.updated_at};}
